FROM golang:1.21 AS building

RUN apt-get update \
    && apt-get install -y git wget

RUN git clone https://github.com/fatedier/frp.git /building

RUN mkdir -p /building/new-conf \
    && wget -O /building/new-conf/frps.ini https://raw.githubusercontent.com/Minsdata/frp-docker/main/conf/frps.ini \
    && wget -O /building/new-conf/frps_full.ini https://raw.githubusercontent.com/Minsdata/frp-docker/main/conf/frps_full.ini


WORKDIR /building

RUN make frps


FROM alpine:latest

RUN apk update --no-cache \
    &&  apk upgrade --no-cache \
    &&  apk add --no-cache curl bash

RUN mkdir -p /app/frps

COPY --from=building /building/bin/frps /usr/bin/frps
COPY --from=building /building/new-conf/frps.ini /app/frps/frps.ini
COPY --from=building /building/new-conf/frps_full.ini /app/frps/frps_full.ini

WORKDIR /app

ENTRYPOINT ["/usr/bin/frps"]

CMD ["-c", "/app/frps/frps.ini"]
