FROM golang:1.21 AS building

RUN apt-get update \
    && apt-get install -y git

RUN git clone https://github.com/fatedier/frp.git /building

WORKDIR /building

RUN make frpc

FROM alpine:latest

RUN apk update --no-cache \
    &&  apk upgrade --no-cache \
    &&  apk add --no-cache curl bash wget

RUN wget -O /frpc/frpc.ini https://github.com/Minsdata/frp-docker/blob/main/conf/frpc.ini \
    && wget -O /frpc/frpc_full.ini https://github.com/Minsdata/frp-docker/blob/main/conf/frpc_full.ini

COPY --from=building /building/bin/frpc /usr/bin/frpc


ENTRYPOINT ["/usr/bin/frpc -c /frpc/frpc.ini"]
