name: Build, Push Docker Images to Dockerhub

on:
  schedule:
    - cron: "0 */6 * * *"
#on:
#  workflow_dispatch:
#    inputs:
#      tag:
#        description: 'Image tag'
#        required: true
#        default: 'test the action'

env:
  PLATFORMS: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v8,linux/arm/v7,linux/arm/v6"
  IMAGE_NAME_PREFIX: "minsdatadocker"

jobs:
  build_and_publish:
    name: Build and Publish Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get FRP Version
        id: get_version
        run: |
          FRP_VERSION=$(curl -s https://api.github.com/repos/fatedier/frp/releases/latest | jq -r .tag_name)
          FRP_VERSION=${FRP_VERSION#v}
          echo "FRP_VERSION=$FRP_VERSION" >> $GITHUB_ENV
      
      - name: Output FRP_VERSION
        run: |
          echo "FRP_VERSION: $FRP_VERSION"
          
      - name: Build and Push FRPS Docker image
        run: |
          DOCKERFILE="./dockerfiles/Dockerfile-for-frps"
          
          docker buildx build -f $DOCKERFILE \
            --build-arg FRP_VERSION=$FRP_VERSION \
            --platform $PLATFORMS \
            -t $IMAGE_NAME_PREFIX/frps:v$FRP_VERSION \
            -t $IMAGE_NAME_PREFIX/frps:latest \
            --push .

      - name: Build and Push FRPC Docker image
        run: |
          DOCKERFILE="./dockerfiles/Dockerfile-for-frpc"
          
          docker buildx build -f $DOCKERFILE \
            --build-arg FRP_VERSION=$FRP_VERSION \
            --platform $PLATFORMS \
            -t $IMAGE_NAME_PREFIX/frpc:v$FRP_VERSION \
            -t $IMAGE_NAME_PREFIX/frpc:latest \
            --push .
