name: Build Image and Publish to Dockerhub & GPR

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test'
permissions:
  contents: read
  
jobs:
  image:
    name: Build Image from Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get latest FRP version
        id: get_version
        run: |
         FRP_VERSION=$(curl -s https://api.github.com/repos/fatedier/frp/releases/latest | jq -r .tag_name)
         FRP_VERSION=${FRP_VERSION#v}  # Remove "v" prefix
         echo "FRP_VERSION=$FRP_VERSION" >> $GITHUB_ENV
      
      - name: Output FRP_VERSION
        run: |
          echo "FRP_VERSION: $FRP_VERSION"
      
      - name: Build Docker image with FRP version
        run: |
         echo "FRP_VERSION: $FRP_VERSION"
         docker buildx build -f ./dockerfiles/Dockerfile-for-frpc --build-arg FRP_VERSION=$FRP_VERSION --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v8,linux/arm/v7,linux/arm/v6 -t minsdatadocker/frpc . --push
         docker buildx build -f ./dockerfiles/Dockerfile-for-frps --build-arg FRP_VERSION=$FRP_VERSION --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v8,linux/arm/v7,linux/arm/v6 -t minsdatadocker/frps . --push
      
   #   - name: Build and push frpc
   #     uses: docker/build-push-action@v4
   #     with:
   #       context: .
   #       file: ./dockerfiles/Dockerfile-for-frpc
   #       platforms: linux/amd64,linux/arm64
   #       push: true
   #       tags: |
   #          minsdatadocker/frpc
   #       build-args: |
   #          FRP_VERSION=$FRP_VERSION
#
#      - name: Build and push frps
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./dockerfiles/Dockerfile-for-frps
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#             minsdatadocker/frps
#          build-args: |
#             FRP_VERSION=$FRP_VERSION
