name: Build and Publish FRP Docker Images

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test the action'

env:
  PLATFORMS: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v8,linux/arm/v7,linux/arm/v6"
  IMAGE_NAME_PREFIX: "minsdatadocker"

jobs:
  build_and_publish:
    name: Build and Publish Images
    runs-on: ubuntu-latest

    steps:
      # ... (your existing steps for building and pushing Docker images)

    - name: Create GZ Archives
      run: |
        ARCHIVE_DIR="./gz_archives"
        mkdir -p $ARCHIVE_DIR
        for frp_arch in $FRP_ARCHS; do
          image_name="${IMAGE_NAME_PREFIX}/frps:${FRP_VERSION}"
          new_image_name="${image_name}_${frp_arch}_v${FRP_VERSION}.gz"
          docker save $image_name | gzip > $ARCHIVE_DIR/$new_image_name
        done

    - name: Upload GZ Archives to GitHub Release
      uses: actions/upload-artifact@v2
      with:
        name: gz-archives
        path: ./gz_archives/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v$FRP_VERSION
        release_name: Release v$FRP_VERSION
        body: This is release v$FRP_VERSION
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.REALSE_TOKEN }}
