name: Release Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test the action'

env:
  PLATFORMS: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v8,linux/arm/v7,linux/arm/v6"
  IMAGE_NAME_PREFIX: "minsdatadocker"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get FRP Version
        run: |
          FRP_VERSION=$(curl -s https://api.github.com/repos/fatedier/frp/releases/latest | jq -r .tag_name)
          FRP_VERSION=${FRP_VERSION#v}
          echo "FRP_VERSION=$FRP_VERSION" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MINSDATA_GITHUB }}
        with:
          tag_name: v${{ env.FRP_VERSION }}
          release_name: Release v${{ env.FRP_VERSION }}
          body: |
             ## Important: Back up your entire instance before using this new version!
             As with any new version, there may be breaking changes. Make sure to backup
             your instance before upgrading to the latest release.

             ## Changes
             Here are the changes in this release:

             ### Docker images
             - Improved performance of Docker images.
             - Updated base image to XYZ version.

             ### Bug Fixes
             - Fixed issue where XYZ feature was not working properly.
             - Addressed security vulnerabilities in ABC component.

             ### Enhancements
             - Added new feature to improve user experience.
             - Enhanced compatibility with XYZ platform.

             ## How to Upgrade
             Follow these steps to upgrade to the latest version:
             1. Backup your current instance.
             2. Download the latest release from [here](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/latest).
             3. Follow the upgrade instructions provided in the documentation.
     
             Thank you for using our software! If you encounter any issues or need assistance,
             feel free to reach out to our support team.
