name: Release Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test the action'

env:
  PLATFORMS: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v8,linux/arm/v7,linux/arm/v6"
  IMAGE_NAME_PREFIX: "minsdatadocker"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get FRP Version
        run: |
          FRP_VERSION=$(curl -s https://api.github.com/repos/fatedier/frp/releases/latest | jq -r .tag_name)
          FRP_VERSION=${FRP_VERSION#v}
          echo "FRP_VERSION=$FRP_VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push FRPS Docker image
        run: |
          DOCKERFILE="./dockerfiles/Dockerfile-for-frps"
          
          docker buildx build -f $DOCKERFILE \
            --build-arg FRP_VERSION=$FRP_VERSION \
            --platform $PLATFORMS \
            -t $IMAGE_NAME_PREFIX/frps:v$FRP_VERSION \
            -t $IMAGE_NAME_PREFIX/frps:latest \
            --push .
          echo "FRPS_IMAGE_TAG=$IMAGE_NAME_PREFIX/frps:v$FRP_VERSION" >> $GITHUB_ENV

      - name: Build and Push FRPC Docker image
        run: |
          DOCKERFILE="./dockerfiles/Dockerfile-for-frpc"
          
          docker buildx build -f $DOCKERFILE \
            --build-arg FRP_VERSION=$FRP_VERSION \
            --platform $PLATFORMS \
            -t $IMAGE_NAME_PREFIX/frpc:v$FRP_VERSION \
            -t $IMAGE_NAME_PREFIX/frpc:latest \
            --push .
          echo "FRPC_IMAGE_TAG=$IMAGE_NAME_PREFIX/frpc:v$FRP_VERSION" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MINSDATA_GITHUB }}
        with:
          tag_name: v${{ env.FRP_VERSION }}
          release_name: Release v${{ env.FRP_VERSION }}
          body: |
             ## Important: Back up your entire instance before using this new version!
             As with any new version, there may be breaking changes. Make sure to backup
             your instance before upgrading to the latest release.

             ## Changes
             Here are the changes in this release:

             ### Docker images
             - Docker image for FRPS: [${{ env.IMAGE_NAME_PREFIX }}/frps:v${{ env.FRP_VERSION }}](${{ env.FRPS_IMAGE_TAG }})
             - Docker image for FRPC: [${{ env.IMAGE_NAME_PREFIX }}/frpc:v${{ env.FRP_VERSION }}](${{ env.FRPC_IMAGE_TAG }})

             ### Bug Fixes
             - Fixed issue where XYZ feature was not working properly.
             - Addressed security vulnerabilities in ABC component.
     
             Thank you for using our software! If you encounter any issues or need assistance,
             feel free to reach out to our support team.
